#!/usr/bin/env python3
"""Generate embedded.c containing compressed c_runtime/ and std/ files.

Usage: python3 scripts/embed.py > /tmp/embedded.c

The output file defines a_embedded_file(AValue) which decompresses and
returns file content by path, or a_void() if not found.
"""

import os
import sys
import zlib

DIRS = ["c_runtime", "std"]
EXTENSIONS = {".c", ".h", ".a"}


def collect_files(base_dirs):
    files = []
    for d in base_dirs:
        for root, _, names in os.walk(d):
            for name in sorted(names):
                if os.path.splitext(name)[1] in EXTENSIONS:
                    files.append(os.path.join(root, name))
    return sorted(files)


def to_varname(path):
    return path.replace("/", "_").replace(".", "_").replace("-", "_")


def compress_raw_deflate(data):
    obj = zlib.compressobj(9, zlib.DEFLATED, -15)
    return obj.compress(data) + obj.flush()


def emit_byte_array(name, data, out):
    out.write(f"static const unsigned char {name}[] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        hex_bytes = ",".join(f"0x{b:02x}" for b in chunk)
        out.write(f"    {hex_bytes},\n")
    out.write("};\n")


def main():
    files = collect_files(DIRS)
    if not files:
        print("error: no files found. Run from the project root.", file=sys.stderr)
        sys.exit(1)

    out = sys.stdout
    out.write("/* Auto-generated by scripts/embed.py -- do not edit */\n")
    out.write('#include "runtime.h"\n')
    out.write('#include "miniz.h"\n')
    out.write("#include <string.h>\n\n")

    entries = []
    for path in files:
        with open(path, "rb") as f:
            raw = f.read()
        compressed = compress_raw_deflate(raw)
        varname = to_varname(path)
        emit_byte_array(varname, compressed, out)
        entries.append((path, varname, len(compressed), len(raw)))
        out.write("\n")

    out.write("typedef struct { const char* path; const unsigned char* data; int clen; int olen; } EmbFile;\n")
    out.write("static const EmbFile emb_files[] = {\n")
    for path, varname, clen, olen in entries:
        out.write(f'    {{"{path}", {varname}, {clen}, {olen}}},\n')
    out.write("    {NULL, NULL, 0, 0}\n")
    out.write("};\n\n")

    out.write("AValue a_embedded_file(AValue path) {\n")
    out.write("    if (path.tag != TAG_STRING) return a_void();\n")
    out.write("    for (int i = 0; emb_files[i].path; i++) {\n")
    out.write('        if (strcmp(emb_files[i].path, path.sval->data) == 0) {\n')
    out.write("            size_t out_len = 0;\n")
    out.write("            void* out = tinfl_decompress_mem_to_heap(\n")
    out.write("                emb_files[i].data, emb_files[i].clen, &out_len, 0);\n")
    out.write("            if (!out) return a_void();\n")
    out.write("            AValue r = a_string_len((const char*)out, (int)out_len);\n")
    out.write("            mz_free(out);\n")
    out.write("            return r;\n")
    out.write("        }\n")
    out.write("    }\n")
    out.write("    return a_void();\n")
    out.write("}\n")

    total_raw = sum(e[3] for e in entries)
    total_comp = sum(e[2] for e in entries)
    print(
        f"/* {len(entries)} files, {total_raw} bytes -> {total_comp} bytes compressed */",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
